### ISSUE TITLE
[Feature] support dbt 1.6

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [godatadriven/pytest-dbt-core#39]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

hi @JCZuurmond ! [dbt-core 1.6 released last week](https://github.com/dbt-labs/dbt-core/releases/tag/v1.6.0); do you plan on supporting it sometime soon? 

if not, we're thinking about submitting a PR to support it since we use your library and we'd like to keep dbt up to date. just checking in before we do duplicative work.

FYI @ybressler

### Are you interested in contributing this feature?

yes

**Comment by JCZuurmond** [comment]
Hi @ConstantinoSchillebeeckx, glad to hear you are using the package. The release is on it is [way](https://github.com/godatadriven/pytest-dbt-core/actions/runs/5813428800). I will check tomorrow if all went well.

**Comment by JCZuurmond** [comment]
The release is there, good luck with testing 😊😉

- [On Github](https://github.com/godatadriven/pytest-dbt-core/releases/tag/0.2.2)
- [On PyPi](https://pypi.org/project/pytest-dbt-core/)
