### ISSUE TITLE
models generator support instead of running a macro

### ISSUE THREAD

**Issue by megetron3** [godatadriven/pytest-dbt-core#49]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

I'm curious if this package allows for the execution of multiple models consecutively. Here's my scenario: I'm utilizing Airflow, and for each data ingestion, I need to pass it through several models. This involves some data canonicalization, followed by enrichment, and finally, business transformation. My preference is to run all these models sequentially, checking the expected results only after all models have been applied to the data, rather than testing each model individually. Can this package accommodate such a workflow?

**Comment by JCZuurmond** [comment]
Hi @megetron3, thanks for opening this issue. Currently this package does not support the use case you describe as unit testing models is not supported by this package. Let's continue the conversation about unit testing models in #12
